import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const testDir = path.dirname(fileURLToPath(import.meta.url));
const mapsDir = path.resolve(testDir, "..");
const html = fs.readFileSync(path.join(mapsDir, "index.html"), "utf8");
const css = fs.readFileSync(path.join(mapsDir, "styles.css"), "utf8");
const app = fs.readFileSync(path.join(mapsDir, "app.js"), "utf8");

assert.ok(!html.includes("点位为国家级聚合，不代表项目坐标"));
assert.ok(html.includes("圆点数字代表项目数量"));
assert.ok(!html.includes("title-rule"));
assert.ok(!html.includes("data.js"));
assert.ok(!html.includes("ExxonMobil"), "shared map HTML must remain company-neutral");
assert.match(html, /styles\.css\?v=20260721-ui-v3-no-header-actions/);
assert.match(html, /app\.js\?v=20260721-ui-v3-no-header-actions/);
assert.match(html, /class="chart-header"/);
assert.ok(!html.includes("chart-actions"));
assert.ok(!html.includes("refresh-button"));
assert.ok(!html.includes("new-window-button"));
assert.ok(!html.includes("fullscreen-button"));
assert.match(html, /id="country-count"/);
assert.match(html, /id="project-filter-toggle"/);
assert.match(html, /id="facility-filter-options"/);
assert.match(html, /id="resource-filter-options"/);
assert.match(html, /id="project-detail-view"/);
assert.match(html, /id="project-detail-back"/);
assert.ok(!html.includes("map-instruction"));
assert.ok(!html.includes("map-status"));
assert.ok(!fs.existsSync(path.join(mapsDir, "data.js")));

assert.match(css, /width:\s*clamp\(500px,\s*60%,\s*640px\)/);
assert.match(css, /max-width:\s*calc\(100%\s*-\s*280px\)/);
assert.match(css, /\.country-dot\.tier-1/);
assert.match(css, /\.country-dot\.is-active[\s\S]*?accent-gold/);
assert.match(css, /\.project-summary-grid/);
assert.match(css, /\.reserve-grid/);
assert.match(css, /\.fact-grid/);
assert.match(css, /@container drawer \(max-width:\s*580px\)[\s\S]*?project-summary-grid/);
const summaryValueRule = css.match(/\.summary-value\s*\{([\s\S]*?)\}/)?.[1] || "";
assert.match(summaryValueRule, /white-space:\s*normal/);
assert.match(summaryValueRule, /overflow-wrap:\s*anywhere/);
assert.match(summaryValueRule, /text-overflow:\s*clip/);
assert.ok(!/height:\s*100v(?:h|svh|dvh)/.test(css));
assert.match(css, /:focus-visible/);

assert.match(app, /\.\/app-core\.js\?v=20260721-ui-v3-no-header-actions/);
assert.ok(!app.includes("refresh-button"));
assert.ok(!app.includes("new-window-button"));
assert.ok(!app.includes("fullscreen-button"));
assert.match(app, /const DATA_ROOT = `\.`/);
assert.match(app, /params\.get\(`operator`\) \|\| `Shell`/);
assert.match(app, /project-summary-grid/);
assert.match(app, /reserve-section/);
assert.match(app, /fact-grid/);
assert.match(app, /listScrollTop/);
assert.match(app, /resources\.rawCounts/);
assert.match(app, /getResourceFilterCounts/);
assert.match(app, /minZoom:\s*1,/);
assert.match(app, /latLngToContainerPoint/);
assert.match(app, /summarizeFieldTypes/);
assert.ok(app.includes("Escape"));
assert.ok(!app.includes("批准年份"));
assert.ok(!app.includes("approvalYears"));

console.log("Map UI V3 contract checks passed");
